name = "gaming-tax-pro"
main = "src/index.js"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "gaming-tax-platform"
database_id = "16f016b2-08df-4bce-9d4d-7f0a7bb4c4f5"
